{
  "openapi" : "3.0.3",
  "info" : {
    "contact" : {
      "email" : "api@contact.name",
      "name" : "api@contact.name"
    },
    "description" : "### Warnings The publication of swaggers makes it possible to set out precisely the interactions that will be possible using the PPF APIs.This is not a production version. These swaggers can be modified later (methods, endpoints).\n- The use of these swaggers will be possible as soon as an application is published on PISTE, which is not the case today.\The API __ppf-openapi-annuaire-api-public__ allows you to:\n- Create, consult, update and search for lines of address:\n- Se[...]",
    "title": "PPF annuaire API public",
    "version": "Increment 2 - Specs Ext 2.2",
    "x-audience": "external-public",
    "x-api-id" : "3230c8a1-f7df-4fa1-8506-24ce034670ce"
  },
  "servers" : [ {
    "description" : "Public directory microservice access url",
    "url" : "https://aife.economie.gouv.fr/ppf/annuaire-public/v1"
  } ],
  "tags" : [ {
    "description" : "Address line in the directory",
    "name" : "Addressing line"
  }, {
    "description" : "Company by Siren number",
    "name" : "Siren"
  }, {
    "description": "Establishment by Siret number",
    "name" : "Siret"
  }, {
    "description" : "Code routage",
    "name" : "Routing code
  }, {
    "description" : "Reserved for supervisor",
    "name" : "Supervisor"
  } ],
  "paths" : {
    "/directory-line" : {
      "post" : {
        "description" : "Create a new addressing line for a SIREN, a SIRET or a ROUTING CODE as well as the associated contract data",
        "operationId" : "createLigneAdressage",
        "security" : [ {
          "bearer_auth" : [ "lineAddressing" ]
        } ],
        "summary" : "Adds an addressing line to the directory",
        "tags" : [ "Address line" ]
      }
    },
    "/directory-line/{id}" : {
      "get" : {
        "description" : "Retrieve the data from the address line corresponding to the identifier passed in parameters",
        "operationId" : "getLigneAdressage",
        "security" : [ {
          "bearer_auth" : [ "lineAddressing" ]
        } ],
        "summary" : "Consult an addressing line in the Directory",
        "tags" : [ "Address line" ]
      },
      "put" : {
        "description" : "Update the status of an addressing line",
        "operationId" : "updateLigneAdressage",
        "security" : [ {
          "bearer_auth" : [ "lineAddressing" ]
        } ],
        "summary" : "Enable/Disable an addressing line",
        "tags" : [ "Address line" ]
      }
    },
    "/directory-line/search" : {
      "post" : {
        "description" : "Search for address lines according to various criteria and return the address lines in the desired format",
        "operationId" : "searchLigneAdressage",
        "security" : [ {
          "bearer_auth" : [ "lineAddressing" ]
        } ],
        "summary" : "Search for addressing lines in the directory",
        "tags" : [ "Address line" ]
      }
    },
    "/siren/{id}" : {
      "get" : {
        "description" : "Returns the details of a company, with SIRETs on request (fields)",
        "operationId" : "getEntreprise",
        "security" : [ {
          "bearer_auth" : [ "siren" ]
        } ],
        "summary" : "Search a company by siren",
        "tags" : [ "siren" ]
      }
    },
    "/siren/search" : {
      "post" : {
        "description" : "Multi-criteria company search",
        "operationId" : "searchEntreprise",
        "security" : [ {
          "bearer_auth" : [ "siren" ]
        } ],
        "summary" : "Multi-criteria company search",
        "tags" : [ "siren" ]
      }
    },
    "/siret/{id}" : {
      "get" : {
        "description" : "Returns the details of an establishment",
        "operationId" : "getEtablissement",
        "security" : [ {
          "bearer_auth" : [ "siret" ]
        } ],
        "summary" : "Consult an establishment by siret",
        "tags" : [ "Siret" ]
      }
    },
    "/siret/search" : {
      "post" : {
        "description" : "Multi-criteria search for establishments",
        "operationId" : "searchEtablissement",
        "security" : [ {
          "bearer_auth" : [ "siret" ]
        } ],
        "summary" : "Multi-criteria search for establishments",
        "tags" : [ "Siret" ]
      }
    },
    "/route-code" : {
      "post" : {
        "description" : "Create a routing code",
        "operationId" : "createCodeRoutage",
        "security" : [ {
          "bearer_auth" : [ "codeRouting" ]
        } ],
        "summary" : "Create a routing code",
        "tags" : [ "RoutingCode" ]
      }
    },
    "/routing-code/{id}" : {
      "delete" : {
        "description" : "Delete a routing code",
        "operationId" : "deleteRoutingCode",
        "security" : [ {
          "bearer_auth" : [ "codeRouting" ]
        } ],
        "summary" : "Delete a routing code",
        "tags" : [ "Routing code" ]
      },
      "get" : {
        "description": "Retrieve the Routing Code data corresponding to the identifier passed in parameters.",
        "operationId" : "getRoutingCode",
        "security" : [ {
          "bearer_auth" : [ "codeRouting" ]
        } ],
        "summary" : "Consult a routing code in the Directory",
        "tags" : [ "Routing code" ]
      },
      "put" : {
        "description" : "Update the status of a routing code",
        "operationId" : "updateRoutingCode",
        "security" : [ {
          "bearer_auth" : [ "codeRouting" ]
        } ],
        "summary" : "Enable/Disable a routing code",
        "tags" : [ "Routing code" ]
      }
    },
    "/routing-code/search" : {
      "post" : {
        "description" : "Search for routing codes according to various criteria and return the routing codes in the desired format",
        "operationId" : "searchCodeRoutage",
        "security" : [ {
          "bearer_auth" : [ "codeRouting" ]
        } ],
        "summary" : "Search for routing codes in the directory",
        "tags" : [ "Routing code" ]
      }
    },
    "/healthcheck" : {
      "get" : {
        "description" : "Check if the API connection is operational",
        "operationId" : "getHealth",
        "security" : [ {
          "bearer_auth" : [ "health.read" ]
        } ],
        "summary" : "Check if the API connection is operational",
        "tags" : [ "Supervisor" ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "bearer_auth" : {
        "bearerFormat" : "JWT",
        "scheme" : "bearer",
        "type" : "http"
      }
    }
  }
}