{
  "openapi" : "3.0.3",
  "info" : {
    "contact" : {
      "email" : "api@contact.name",
      "name" : "api@contact.name"
    },
    "description" : "### Avertissements\n- La publication des swaggers permet d’exposer de manière précise les interactions qui seront possibles à l'aide des API du PPF.\n- Il ne s’agit pas d’une version de production. Ces swaggers pourront être modifiés ultérieurement (méthodes, endpoints).\n- L’utilisation de ces swaggers sera possible dés lors qu’une application sera publiée sur PISTE, ce qui n'est pas le cas ce jour.\n---\n---\n# ppf-openapi-annuaire-api-public\n\nL’API __ppf-openapi-annuair[...]",
    "title" : "PPF annuaire API public",
    "version" : "Incrément 2 - Specs Ext 2.2",
    "x-audience" : "external-public",
    "x-api-id" : "3230c8a1-f7df-4fa1-8506-24ce034670ce"
  },
  "servers" : [ {
    "description" : "Url d’accès au micro-service annuaire public",
    "url" : "https://aife.economie.gouv.fr/ppf/annuaire-public/v1"
  } ],
  "tags" : [ {
    "description" : "Ligne d’adressage dans l’annuaire",
    "name" : "Ligne d’adressage"
  }, {
    "description" : "Entreprise par numéro de Siren",
    "name" : "Siren"
  }, {
    "description" : "Établissement par numéro de Siret",
    "name" : "Siret"
  }, {
    "description" : "Code routage",
    "name" : "Code routage"
  }, {
    "description" : "Réservé au superviseur",
    "name" : "Superviseur"
  } ],
  "paths" : {
    "/ligne-annuaire" : {
      "post" : {
        "description" : "Créer une nouvelle ligne d'adressage pour un SIREN, un SIRET ou un CODE ROUTAGE ainsi que les données du contrat associé.",
        "operationId" : "createLigneAdressage",
        "security" : [ {
          "bearer_auth" : [ "ligneAdressage" ]
        } ],
        "summary" : "Ajoute une ligne d’adressage dans l’annuaire.",
        "tags" : [ "Ligne d’adressage" ]
      }
    },
    "/ligne-annuaire/{id}" : {
      "get" : {
        "description" : "Récupérer les données de la ligne d’adressage correspondante à l’identifiant passé en paramètres.",
        "operationId" : "getLigneAdressage",
        "security" : [ {
          "bearer_auth" : [ "ligneAdressage" ]
        } ],
        "summary" : "Consulter une ligne d’adressage dans l’Annuaire.",
        "tags" : [ "Ligne d’adressage" ]
      },
      "put" : {
        "description" : "Permet de mettre à jour le status d’une ligne d’adressage.",
        "operationId" : "updateLigneAdressage",
        "security" : [ {
          "bearer_auth" : [ "ligneAdressage" ]
        } ],
        "summary" : "Activer/Désactiver une ligne d’adressage.",
        "tags" : [ "Ligne d’adressage" ]
      }
    },
    "/ligne-annuaire/recherche" : {
      "post" : {
        "description" : "Rechercher des lignes d’adressage selon différents critères et retourne les lignes d’adressage au format souhaité.",
        "operationId" : "searchLigneAdressage",
        "security" : [ {
          "bearer_auth" : [ "ligneAdressage" ]
        } ],
        "summary" : "Recherche des lignes d’adressage dans l’annuaire.",
        "tags" : [ "Ligne d’adressage" ]
      }
    },
    "/siren/{id}" : {
      "get" : {
        "description" : "Retourne le détail d'une entreprise, avec les SIRET sur demande (fields).",
        "operationId" : "getEntreprise",
        "security" : [ {
          "bearer_auth" : [ "siren" ]
        } ],
        "summary" : "Consulter une entreprise selon un siren.",
        "tags" : [ "Siren" ]
      }
    },
    "/siren/recherche" : {
      "post" : {
        "description" : "Recherche multi-critères d'entreprises.",
        "operationId" : "searchEntreprise",
        "security" : [ {
          "bearer_auth" : [ "siren" ]
        } ],
        "summary" : "Recherche multi-critères d'entreprises.",
        "tags" : [ "Siren" ]
      }
    },
    "/siret/{id}" : {
      "get" : {
        "description" : "Retourne le détail d'un établissement.",
        "operationId" : "getEtablissement",
        "security" : [ {
          "bearer_auth" : [ "siret" ]
        } ],
        "summary" : "Consulter un établissement selon un siret.",
        "tags" : [ "Siret" ]
      }
    },
    "/siret/recherche" : {
      "post" : {
        "description" : "Recherche multi-critères d'établissements.",
        "operationId" : "searchEtablissement",
        "security" : [ {
          "bearer_auth" : [ "siret" ]
        } ],
        "summary" : "Recherche multi-critères d'établissements.",
        "tags" : [ "Siret" ]
      }
    },
    "/code-routage" : {
      "post" : {
        "description" : "Crée un code routage",
        "operationId" : "createCodeRoutage",
        "security" : [ {
          "bearer_auth" : [ "codeRoutage" ]
        } ],
        "summary" : "Crée un code routage",
        "tags" : [ "Code routage" ]
      }
    },
    "/code-routage/{id}" : {
      "delete" : {
        "description" : "Supprimer un code routage.",
        "operationId" : "deleteCodeRoutage",
        "security" : [ {
          "bearer_auth" : [ "codeRoutage" ]
        } ],
        "summary" : "Supprimer un code routage.",
        "tags" : [ "Code routage" ]
      },
      "get" : {
        "description" : "Récupérer les données de la Code Routage correspondante à l’identifiant passé en paramètres.",
        "operationId" : "getCodeRoutage",
        "security" : [ {
          "bearer_auth" : [ "codeRoutage" ]
        } ],
        "summary" : "Consulter un code routage dans l’Annuaire.",
        "tags" : [ "Code routage" ]
      },
      "put" : {
        "description" : "Permet de mettre à jour le status d’un code routage.",
        "operationId" : "updateCodeRoutage",
        "security" : [ {
          "bearer_auth" : [ "codeRoutage" ]
        } ],
        "summary" : "Activer/Désactiver un code routage.",
        "tags" : [ "Code routage" ]
      }
    },
    "/code-routage/recherche" : {
      "post" : {
        "description" : "Rechercher des codes routage selon différents critères et retourne les codes routage au format souhaité.",
        "operationId" : "searchCodeRoutage",
        "security" : [ {
          "bearer_auth" : [ "codeRoutage" ]
        } ],
        "summary" : "Recherche des codes routage dans l’annuaire.",
        "tags" : [ "Code routage" ]
      }
    },
    "/healthcheck" : {
      "get" : {
        "description" : "Vérifier si la connexion API est opérationnelle.",
        "operationId" : "getHealth",
        "security" : [ {
          "bearer_auth" : [ "health.read" ]
        } ],
        "summary" : "Vérifier si la connexion API est opérationnelle.",
        "tags" : [ "Superviseur" ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "bearer_auth" : {
        "bearerFormat" : "JWT",
        "scheme" : "bearer",
        "type" : "http"
      }
    }
  }
}